# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

executors:
  build:
    parameters:
      go-version:
        type: string
      go-modules-enabled:
        type: string
    docker:
      - image: circleci/golang:<< parameters.go-version >>
        environment:
          GO111MODULE: << parameters.go-modules-enabled >>
    working_directory: /go/src/github.com/terakoya76/populator

commands:
  go_mod_download:
    steps:
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  build:
    steps:
      - run:
          name: Build source
          command: go build

  lint:
    steps:
      - run:
          name: Run GolangCI-Lint
          command: make lint
      - run:
          name: Run gofmt
          command: diff -u <(echo -n) <(gofmt -d -s .)

  test:
    steps:
      - run:
          name: Run Tests
          command: go test -race -v ./...

jobs:
  go-current:
    parameters:
      go-version:
        type: string
      go-modules-enabled:
        type: string
    executor:
      name: build
      go-version: << parameters.go-version >>
      go-modules-enabled: << parameters.go-modules-enabled >>
    steps:
      - checkout
      - go_mod_download
      - build
      - lint
      - test

  go-previous:
    parameters:
      go-version:
        type: string
      go-modules-enabled:
        type: string
    executor:
      name: build
      go-version: << parameters.go-version >>
      go-modules-enabled: << parameters.go-modules-enabled >>
    steps:
      - checkout
      - run:
          name: Install dependencies without go-modules
          command: go get -t -v ./...
      - build
      - test

  go-latest:
    parameters:
      go-version:
        type: string
      go-modules-enabled:
        type: string
    executor:
      name: build
      go-version: << parameters.go-version >>
      go-modules-enabled: << parameters.go-modules-enabled >>
    steps:
      - checkout
      - go_mod_download
      - build
      - test

workflows:
  version: 2
  main:
    jobs:
      - go-current:
          go-version: "1.12"
          go-modules-enabled: "on"
      - go-previous:
          go-version: "1.11"
          go-modules-enabled: "off"
      - go-latest:
          go-version: "latest"
          go-modules-enabled: "on"
